package org.com.techsalesmanagerclient.enums;

public enum RequestType {
    AUTHORIZATION,
    GET_ALL_CATEGORIES,
    ADD_CATEGORY,
    UPDATE_CATEGORY,
    REMOVE_CATEGORY,
    GET_ALL_SUPPLIERS,
    ADD_SUPPLIER,
    UPDATE_SUPPLIER,
    REMOVE_SUPPLIER,
    GET_ALL_CUSTOMERS,
    ADD_CUSTOMER,
    UPDATE_CUSTOMER,
    GET_ALL_USERS, HANDLE_CREATE, CREATE_USER, SEARCH_USER, REMOVE_CUSTOMER
}