package org.com.techsalesmanagerserver.enumeration;

public enum RequestType {
    // User operations
    AUTHORIZATION,
    REGISTRATION,
    CREATE_USER,
    DELETE_USER,
    UPDATE_USER,
    SEARCH_USER,
    GET_ALL_USERS,
    FILTER_USER_BY_ID,
    FILTER_USER_BY_EMAIL,

    // Category operations
    CREATE_CATEGORY,
    DELETE_CATEGORY,
    UPDATE_CATEGORY,
    SEARCH_CATEGORY,
    GET_ALL_CATEGORIES,
    FILTER_CATEGORY_BY_ID,
    FILTER_CATEGORY_BY_NAME,

    // Product operations
    CREATE_PRODUCT,
    DELETE_PRODUCT,
    UPDATE_PRODUCT,
    SEARCH_PRODUCT,
    GET_ALL_PRODUCTS,
    FILTER_PRODUCT_BY_ID,
    FILTER_PRODUCT_BY_NAME,
    FILTER_PRODUCT_BY_CATEGORY,
    FILTER_PRODUCT_BY_SUPPLIER,

    // Order operations
    CREATE_ORDER,
    DELETE_ORDER,
    UPDATE_ORDER,
    SEARCH_ORDER,
    GET_ALL_ORDERS,
    FILTER_ORDER_BY_ID,
    FILTER_ORDER_BY_USER,
    FILTER_ORDER_BY_STATUS,
    FILTER_ORDER_BY_DATE_RANGE,

    // OrderItem operations
    CREATE_ORDER_ITEM,
    DELETE_ORDER_ITEM,
    UPDATE_ORDER_ITEM,
    SEARCH_ORDER_ITEM,
    GET_ALL_ORDER_ITEMS,
    FILTER_ORDER_ITEM_BY_ID,
    FILTER_ORDER_ITEM_BY_ORDER,
    FILTER_ORDER_ITEM_BY_PRODUCT,

    // Supplier operations
    CREATE_SUPPLIER,
    DELETE_SUPPLIER,
    UPDATE_SUPPLIER,
    SEARCH_SUPPLIER,
    GET_ALL_SUPPLIERS,
    FILTER_SUPPLIER_BY_ID,
    FILTER_SUPPLIER_BY_NAME,
    FILTER_SUPPLIER_BY_PRODUCT,
    ADD_PRODUCT_TO_SUPPLIER,
    REMOVE_PRODUCT_FROM_SUPPLIER,
    GET_SUPPLIER_PRODUCTS
} 